# Generated by Django 5.1 on 2024-09-29 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_comments_author_alter_comments_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='caption_ru',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AddField(
            model_name='posts',
            name='caption_uz',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
